"""migration database

Revision ID: 67ab4f746fbb
Revises: 9f6f6d0dae91
Create Date: 2024-07-15 13:37:58.184638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ab4f746fbb'
down_revision = '9f6f6d0dae91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periode', sa.String(length=250), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('headline', sa.String(length=250), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=True),
    sa.Column('predik', sa.String(length=100), nullable=True),
    sa.Column('verif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('berita')
    # ### end Alembic commands ###
