"""membuat tabel berita

Revision ID: 69ab01791d69
Revises: 9d73a39e8a4f
Create Date: 2024-07-15 12:17:29.779756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ab01791d69'
down_revision = '9d73a39e8a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periode', sa.String(length=250), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('headline', sa.String(length=250), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('predik', sa.String(length=100), nullable=True),
    sa.Column('verif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('berita')
    # ### end Alembic commands ###
