"""buat tabel testing

Revision ID: 9d73a39e8a4f
Revises: 40347dd6070e
Create Date: 2024-07-12 11:42:56.656736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d73a39e8a4f'
down_revision = '40347dd6070e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('periode', sa.String(length=250), nullable=False),
    sa.Column('judul', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sentimen', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    # ### end Alembic commands ###
