"""tambah kolom sentimen

Revision ID: aaf9437b731c
Revises: 67ab4f746fbb
Create Date: 2024-07-19 14:39:17.200669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf9437b731c'
down_revision = '67ab4f746fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('berita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentimen', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('berita', schema=None) as batch_op:
        batch_op.drop_column('sentimen')

    # ### end Alembic commands ###
